import type { Metadata } from "next";
import { Playfair_Display as Font } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/navBar";

const font = Font({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "FotoComparendo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body
        className={
          font.className +
          "relative h-screen w-screen overflow-x-hidden scrollbar-thin scrollbar-thumb-slate-500 scrollbar-thumb-rounded-full"
        }
      >
        <NavBar />
        {children}
      </body>
    </html>
  );
}
